name       : python-notebook-shim
version    : 0.2.2
release    : 1
source     :
    - https://files.pythonhosted.org/packages/source/n/notebook_shim/notebook_shim-0.2.2.tar.gz : 090e0baf9a5582ff59b607af523ca2db68ff216da0c69956b62cab2ef4fc9c3f
homepage   : https://github.com/jupyter/notebook_shim
license    : BSD-3-Clause
component  : programming.python
summary    : A shim layer for notebook traits and config
description: |
    This project provides a way for JupyterLab and other frontends to switch to Jupyter Server for their Python Web application backend.
builddeps  :
    - python-build
    - python-hatchling
    - python-installer
rundeps    :
    - python-jupyter-server
build      : |
    %python3_setup
install    : |
    %python3_install
